"""empty message

Revision ID: 64951165525e
Revises: fe0937995a14
Create Date: 2024-06-29 23:42:59.053043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64951165525e'
down_revision = 'fe0937995a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_group', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
