"""empty message

Revision ID: 73364b36a91e
Revises: c1cedeb0a821
Create Date: 2024-06-16 23:17:18.211784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73364b36a91e'
down_revision = 'c1cedeb0a821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lv1', sa.String(length=200), nullable=True),
    sa.Column('account', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curVer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('selectedMM', sa.String(length=2), nullable=True),
    sa.Column('toMM', sa.String(length=2), nullable=True),
    sa.Column('company', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dontForget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('finished', sa.String(length=1), nullable=True),
    sa.Column('amt_tot', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_jan', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_feb', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_mar', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_apr', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_may', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_jun', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_jul', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_aug', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_sep', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_oct', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_nov', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amt_dec', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elimination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('account', sa.String(length=200), nullable=True),
    sa.Column('jan', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('feb', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('mar', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('apr', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('may', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('jun', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('jul', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('aug', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('sep', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('oct', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('nov', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('dec', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('tot_month', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ex_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('mm', sa.String(length=2), nullable=True),
    sa.Column('curr', sa.String(length=3), nullable=True),
    sa.Column('rate', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('fxinput', sa.String(length=1), nullable=True),
    sa.Column('fxfinish', sa.String(length=1), nullable=True),
    sa.Column('getttl', sa.String(length=1), nullable=True),
    sa.Column('getothers', sa.String(length=1), nullable=True),
    sa.Column('getfinal', sa.String(length=1), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('salesplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('mm', sa.String(length=2), nullable=True),
    sa.Column('salesDivision', sa.String(length=20), nullable=True),
    sa.Column('amount_EA', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amount_weight', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('amount_sales', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', 'year', 'mm', 'salesDivision')
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('mm', sa.String(length=2), nullable=True),
    sa.Column('tomm', sa.String(length=2), nullable=True),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'mm', 'version')
    )
    op.create_table('test_excel2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('mm', sa.String(length=2), nullable=True),
    sa.Column('company', sa.String(length=4), nullable=True),
    sa.Column('curr', sa.String(length=3), nullable=True),
    sa.Column('Sales', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('CGS', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('CGM', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Freight', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Insure_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('GP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('SalesExpences', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Agent_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Agent_inland', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Moving_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Moving_inland', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Insure_PL', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Comp_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Comp_inland', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Packing_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Packing_inland', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Royalty_inland', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Royalty_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Advertisement_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Advertisement_inland', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OperatingProfit1', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('AdminExpences', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('SalaryBOD', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Salary', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Pension', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('EmployBenefit', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Travel', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Telecommunication', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Utilities', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('TaxesAndDues', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Rent', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Depreciation', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Amortization', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Maintanance', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Insurance', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Entertainment', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('SampleFee', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('TransportFee', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Commission', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Service', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('BedDept', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Consumable', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Training', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('BooksAndPrinting', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Vehicle', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Conference', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Miscellaneous', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Overseas', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Warehouse', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('ReversalBadDebt', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('ResearchDevelopment', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('LeaseAmortization', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OperatingProfit2', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('NonOperatingRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FinancialRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('InterestRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('TradingSecuritiesInterest', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxRevenue_Operating', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxIncone_NonOp', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DerivativesRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('TradingSecuritiesRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OtherNonOPRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DividentRevenue', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('MiscellaneousProfit', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Gain_disposal_assets', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Gain_OtherNonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('ReversalNRV', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('ReversalOtherAllowance', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('NonOperatingEnpences', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FinancialCost', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Interest', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('BondInterest', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('LossDisposalAR', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxLoss_Operating', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxLoss_NonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DerivativesLoss_tot', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DerivativesLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('TradingSecuritiesLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OtherNonOPLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Donation', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Loss_disposal_assets', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Loss_disposal_inventory', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Loss_OtherNonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('MiscellaneousLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OtherAllowance', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OrdinaryIncome1', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Gain_disposal_assets_NonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DebtForgiveness', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('LeaseInterestIncome', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OtherSpecialGain', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Loss_disposal_assets_NonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DebtForgivenessAmortization', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('LeaseInterestCost', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OtherSpecialLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('ValuationLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OrdinaryIncome2', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxValuation', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxValuationGain_OP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxValuationGain_NonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxValuationLoss_OP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('FxValuationLoss_NonOP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DerivativesVauation', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DerivativesVauationGain', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DerivativesVauationLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OrdinaryIncome3', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('SecuritiesGain', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('SecuritiesLoss', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OrdinaryIncome4', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Tax', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('NetIncome', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_excel2')
    op.drop_table('version')
    op.drop_table('salesplan')
    op.drop_table('procedure')
    op.drop_table('ex_rate')
    op.drop_table('elimination')
    op.drop_table('dontForget')
    op.drop_table('curVer')
    op.drop_table('account_group')
    # ### end Alembic commands ###
