"""empty message

Revision ID: 783026b24269
Revises: f33922b46186
Create Date: 2024-07-13 22:26:36.025443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783026b24269'
down_revision = 'f33922b46186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Group_lv1_code', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('Group_lv2_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('Group_lv3_code', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('Group_lv4_code', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_group', schema=None) as batch_op:
        batch_op.drop_column('Group_lv4_code')
        batch_op.drop_column('Group_lv3_code')
        batch_op.drop_column('Group_lv2_code')
        batch_op.drop_column('Group_lv1_code')

    # ### end Alembic commands ###
