"""empty message

Revision ID: 92c6118a9136
Revises: 73364b36a91e
Create Date: 2024-06-23 21:38:21.523560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c6118a9136'
down_revision = '73364b36a91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('mm', sa.String(length=2), nullable=True),
    sa.Column('SalesType', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=4), nullable=True),
    sa.Column('companyName', sa.String(length=40), nullable=True),
    sa.Column('SalesGroup', sa.String(length=3), nullable=True),
    sa.Column('SalesGroupName', sa.String(length=100), nullable=True),
    sa.Column('DistributeChannel', sa.String(length=2), nullable=True),
    sa.Column('DistributeChannelName', sa.String(length=100), nullable=True),
    sa.Column('Usage', sa.String(length=20), nullable=True),
    sa.Column('Origin', sa.String(length=20), nullable=True),
    sa.Column('ProdPlant', sa.String(length=20), nullable=True),
    sa.Column('ProdGrp', sa.String(length=2), nullable=True),
    sa.Column('ProdGrpName', sa.String(length=40), nullable=True),
    sa.Column('Rim', sa.String(length=5), nullable=True),
    sa.Column('subGroup', sa.String(length=8), nullable=True),
    sa.Column('HVP', sa.String(length=20), nullable=True),
    sa.Column('HVP2', sa.String(length=20), nullable=True),
    sa.Column('curr', sa.String(length=3), nullable=True),
    sa.Column('EA', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('Weight', sa.Numeric(precision=13, scale=2), nullable=True),
    sa.Column('Sales', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('CGS', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('CGM', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Material', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DirectLabor', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('IndirectLabor', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('DirectOH', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('IndirectOH', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Freight', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('Insure_ex', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('CGS_other', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('CustomReturn', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('GP', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('SalesExpences', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('AdminExpences', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('OperatingProfit2', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_record')
    # ### end Alembic commands ###
