"""empty message

Revision ID: c7f774b915af
Revises: 783026b24269
Create Date: 2024-08-10 14:14:17.120395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7f774b915af'
down_revision = '783026b24269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ex_rate', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=mysql.DECIMAL(precision=22, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ex_rate', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=mysql.DECIMAL(precision=22, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
