"""empty message

Revision ID: d8728da757df
Revises: 92c6118a9136
Create Date: 2024-06-29 21:43:32.056161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8728da757df'
down_revision = '92c6118a9136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SalesGroup', sa.String(length=3), nullable=True),
    sa.Column('DistributeChannel', sa.String(length=2), nullable=True),
    sa.Column('Group_lv1', sa.String(length=30), nullable=True),
    sa.Column('Group_lv2', sa.String(length=30), nullable=True),
    sa.Column('Group_lv3', sa.String(length=30), nullable=True),
    sa.Column('Group_lv4', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_record', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    op.drop_table('sales_group')
    # ### end Alembic commands ###
