"""empty message

Revision ID: fe0937995a14
Revises: d8728da757df
Create Date: 2024-06-29 22:33:36.688804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0937995a14'
down_revision = 'd8728da757df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yyyymm', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_record', schema=None) as batch_op:
        batch_op.drop_column('yyyymm')

    # ### end Alembic commands ###
